name: citronix
services:
  postgres:
    container_name: citronix_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=citronix'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
